#!/usr/bin/env bash

exit_err() {
    [ "$1" != "" ] && echo >&2 "${1}"
    exit 1
}

awsp() {
    if [ "$1" = "" ]; then
        export AWS_PROFILE="$(aws configure list-profiles | fzy || exit_err '^C')"
    elif [ "$1" = "on" ]; then
        export PS1_AWSP="on"
    elif [ "$1" = "off" ]; then
        export PS1_AWSP=""
    fi
}

aws_ps1() {
    which aws &> /dev/null || return
    if [ "$PS1_AWSP" = "on" -a "$AWS_PROFILE" != "" ]; then
        echo "☁$AWS_PROFILE"
    elif [ "$PS1_AWSP" = "on" -a "$AWS_PROFILE" = "" ]; then
        echo "☁NOT SET"
    else
        echo ""
    fi
}

kctx() {
    if [ "$1" = "" ]; then
        kubectl config use-context "$(kubectl config get-contexts -o name | fzy || exit_err '^C')"
    elif [ "$1" = "on" ]; then
        export PS1_KCTX="on"
    elif [ "$1" = "off" ]; then
        export PS1_KCTX=""
    fi
}

kns() {
    if [ "$1" != "" ]; then
        kubectl config set-context --current --namespace $1
    else
        kubectl config set-context --current --namespace \
                $(kubectl get namespaces -o=custom-columns=NAME:.metadata.name | fzy || exit_err '^C')
    fi
}

git_branch_ps1() {
    echo "$(git branch 2>/dev/null | grep -e '\* ' | sed 's/^..\(.*\)/{\1}/')"
}

get_current_namespace() {
    ctx="$(kubectl config current-context)"
    ns="$(kubectl config view -o=jsonpath="{.contexts[?(@.name==\"${ctx}\")].context.namespace}")"
    echo "$ns"
}

kctx_ps1() {
    which kubectl &> /dev/null || return
    ctx="$(kubectl config current-context 2> /dev/null)"

    if [ "$PS1_KCTX" = "on" -a "$ctx" != "" ]; then
        echo "⎈$ctx/$(get_current_namespace)"
    elif [ "$PS1_KCTX" = "on" -a "$ctx" = "" ]; then
        echo "⎈NOT SET"
    else
        echo ""
    fi
}

bash_prompt() {
    result=$?
    status="$result $(date +'%F %T')"
    reverse_color="\[\033[0;7m\]"
    normal_color="\[\033[0m\]"
    blue_color="\[\033[0;37;44m\]"
    green_color="\[\033[0;42m\]"
    yellow_color="\[\033[0;43m\]"
    red_color="\[\033[0;41m\]"

    if [ "$result" = "0" ]; then
        status_color=$yellow_color;
    else
        status_color=$red_color;
    fi

    PS1="$status_color${status}$reverse_color \w $green_color\$(git_branch_ps1)\
$blue_color$(kctx_ps1)$(aws_ps1)$reverse_color$(printf '\n$')$normal_color "
}

PROMPT_COMMAND=bash_prompt
