#!/bin/bash
settings_path=$(dirname $0)

diff_file=/tmp/install.diff
diff_cp() {
	if [ -z "$1" -o -z "$2" ]; then
		return 0
	fi

	if [ ! -e $2 ]; then
		$3 cp $1 $2
	fi
	
	diff -u $2 $1 > $diff_file
	local diff_return=$?
	if [ $diff_return -eq 0 ]; then
		return 1
	fi

	while [ 1 ]; do
		echo cp: overwrite "'$2' [Y/n/d(diff)]? "
		read choice
		if [ "$choice" = "Y" -o "$choice" = "y" ]; then
			$3 cp $1 $2
			return 2
		elif [ "$choice" = "N" -o "$choice" = "n" ]; then
			return 3
		elif [ "$choice" = "d" ]; then
			less $diff_file
		fi
	done
}

fge() {
	awk -v n1=$1 -v n2=$2 'BEGIN{ if (n1 >= n2) exit 0; exit 1 }'
}

echo -ne "emacs setting...\r"

if [ ! -d ~/.emacs.d/snippets ]; then
	ln -s $PWD/$settings_path/emacs/snippets ~/.emacs.d/snippets
fi

diff_cp $settings_path/emacs/.emacs ~/.emacs

fc-list | grep NanumGothic_AndaleMono > /dev/null
if [ $? -eq 0 ]; then
	diff_cp $settings_path/emacs/linux/.Xresources ~/.Xresources
fi

# emacs --batch -f batch-byte-compile ~/.emacs 2> ~/.emacs.elc.log
echo emacs setting... OK

echo -ne "vim setting...\r"
diff_cp $settings_path/vim/.vimrc ~/.vimrc
echo vim setting... OK

echo -ne "xmodmap setting...\r"
diff_cp $settings_path/xmodmap/.Xmodmap ~/.Xmodmap
echo xmodmap setting... OK

# comment out to resolve the deprecated warning on Debian 7.0 testing
# echo -ne "font setting...\r"
# diff_cp $settings_path/fonts/.fonts.conf ~/.config/fontconfig/fonts.conf
# diff_cp $settings_path/fonts/.fonts.conf ~/.fonts.conf
# echo font setting... OK

echo -ne "git setting...\r"
diff_cp $settings_path/git/.gitconfig ~/.gitconfig

git_version=`git --version | cut -d ' ' -f 3`
if fge $git_version 1.7.11; then
	git config --global push.default simple
else
	git config --global push.default current
fi

echo git setting... OK

echo -ne "gdb setting...\r"
diff_cp $settings_path/gdb/.gdbinit ~/.gdbinit
echo gdb setting... OK

echo -ne "lldb setting...\r"
diff_cp $settings_path/lldb/.lldbinit ~/.lldbinit
echo lldb setting... OK

if [ -d ~/.moc ]; then
	echo -ne "moc setting...\r"
	diff_cp $settings_path/moc/config ~/.moc/config
	echo moc setting... OK
fi

if [ -d ~/.mplayer ]; then
	echo -ne "mplayer setting...\r"
	diff_cp $settings_path/mplayer/config ~/.mplayer/config
	echo mplayer setting... OK
fi

if [ -d ~/.config/terminator ]; then
	echo -ne "terminator setting...\r"
	diff_cp $settings_path/terminator/config ~/.config/terminator/config
	echo terminator setting... OK
fi

if [ -d ~/.config/openbox ]; then
	echo -ne "openbox setting...\r"
	diff_cp $settings_path/openbox/environment ~/.config/openbox/environment
	diff_cp $settings_path/openbox/autostart.sh ~/.config/openbox/autostart.sh
	diff_cp $settings_path/openbox/rc.xml ~/.config/openbox/rc.xml
	echo openbox setting... OK
fi

if [ "`which stumpwm 2> /dev/null`" != "" ]; then
	echo "StumpWM setting..."
	diff_cp $settings_path/stumpwm/.stumpwmrc ~/.stumpwmrc
	diff_cp $settings_path/stumpwm/stumpwm.desktop /usr/share/xsessions/stumpwm.desktop sudo
	echo StumpWM setting... OK
fi

if [ "`which tmux 2> /dev/null`" != "" ]; then
	echo "tmux setting..."
	diff_cp $settings_path/tmux/.tmux.conf ~/.tmux.conf
	echo tmux setting... OK
fi

if [ "`which conkeror 2> /dev/null`" != "" ]; then
	echo -ne "conkeror setting...\r"
	diff_cp $settings_path/conkeror/.conkerorrc ~/.conkerorrc

	# make conkeror bookmarks synchronize with firefox bookmarks
	firefox_config_path=~/.mozilla/firefox
	conkeror_config_path=~/.conkeror.mozdev.org/conkeror
	if [ -d $firefox_config_path -a -d $conkeror_config_path ]; then
		firefox_bookmarks=$firefox_config_path/$(cat $firefox_config_path/profiles.ini | grep Path | awk 'BEGIN { FS = "=" } { print $2 }')
		conkeror_bookmarks=$conkeror_config_path/$(cat $conkeror_config_path/profiles.ini | grep Path | awk 'BEGIN { FS = "=" } { print $2 }')
		cp $firefox_bookmarks/places.sqlite $conkeror_bookmarks/places.sqlite
	fi
	echo conkeror setting... OK
fi

if [ -f /Applications/Slate.app/Contents/MacOS/Slate ]; then
	echo -ne "Slate settings...\r"
	diff_cp $settings_path/slate/.slate ~/.slate
	echo Slate settings... OK
fi
