#!/bin/bash
site_lisp_path=$(dirname $0)

android_path="$site_lisp_path/android.el"
android_download=""
android_install=""

auto_complete_path="$site_lisp_path/auto-complete-1.3/"
auto_complete_download="wget http://cx4a.org/pub/auto-complete/auto-complete-1.3.tar.bz2"
auto_complete_install="tar xjf auto-complete-1.3.tar.bz2"

ecb_path="$site_lisp_path/ecb/"
ecb_download="cvs -d:pserver:anonymous@ecb.cvs.sourceforge.net:/cvsroot/ecb login"
ecb_install="cvs -z3 -d:pserver:anonymous@ecb.cvs.sourceforge.net:/cvsroot/ecb co ecb"

ruby_mode_path="$site_lisp_path/ruby-mode/"
ruby_mode_download="svn co http://svn.ruby-lang.org/repos/ruby/trunk/misc ruby-mode"
ruby_mode_install=""

w3m_path="$site_lisp_path/emacs-w3m/"
w3m_download="cvs -d :pserver:anonymous@cvs.namazu.org:/storage/cvsroot login"
w3m_install="cvs -d :pserver:anonymous@cvs.namazu.org:/storage/cvsroot co emacs-w3m"

xcode_document_path="$site_lisp_path/emacs-xcode-document-viewer/"
xcode_document_download="git clone http://github.com/imakado/emacs-xcode-document-viewer.git"
xcode_document_install=""

usage() {
	echo Emacs Lisp Installation Tool
	echo 
	echo Usage: elit package-name
	echo
	echo Packages:
	echo "  all(all packages)"
	echo "  android"
	echo "  auto-complete"
	echo "  ecb"
	echo "  highlight-symbol"
	echo "  rdebug"
	echo "  ruby-mode"
	echo "  xcscope"
	echo "  w3m"
	echo "  xcode-document"
}

install() {
	if [ -z "$1" ]; then
		return 1
	fi
	eval path=\$$1_path
	if [ -e $path ]; then
		echo Already installed!!!
		return 2
	fi
	
	echo "---> downloading..."
	eval download=\$$1_download
	if [ -n "$download" ]; then
		echo "---> $download"
		ret=$($download)
	fi
	
	echo "---> installing..."
	eval install=\$$1_install
	if [ -n "$install" ]; then
		echo "---> $install"
		ret=$($install)
	fi

	return 0;
}

if [ $# -eq 0 ]; then
	usage
	exit
fi
cd $site_lisp_path

echo "---> $1 installing..."

case "$1" in
	"android")
		install "android"
		;;
	"auto-complete")
		install "auto_complete"
		;;
	"ecb")
		install "ecb"
		;;
	"ruby-mode")
		install "ruby_mode"
		;;
	"w3m")
		install "w3m"
		;;
	"xcode-document")
		install "xcode_document"
		;;
	*)
		usage
		;;
esac	
