#!/bin/bash

require() {
	echo "deferred"
}

description() {
	echo ""
}

target() {
	echo "$TARGET_DIR/c-eldoc.el"
}

install() {
	wget --no-check-certificate http://github.com/mooz/c-eldoc/raw/master/c-eldoc.el
}

remove() {
	rm -vrf $(target)
}

eval $1
