#!/bin/bash

require() {
	echo ""
}

description() {
	echo ""
}

target() {
	echo "$TARGET_DIR/cedet-1.0pre7"
}

install() {
	wget http://sourceforge.net/projects/cedet/files/cedet/1.0pre7/cedet-1.0pre7.tar.gz
	tar xzf cedet-1.0pre7.tar.gz
}

remove() {
	rm -vrf $(target)
}

eval $1
