#!/bin/bash

require() {
	echo ""
}

description() {
	echo "Drop-down menu interface"
}

target() {
	echo "$TARGET_DIR/dropdown-list.el"
}

install() {
	wget http://www.emacswiki.org/emacs/download/dropdown-list.el &&
	patch -p1 -i dropdown-list.patch
}

remove() {
	rm -vrf $(target)
}

eval $1
