#!/bin/bash

require() {
	echo ""
}

description() {
	echo ""
}

target() {
	echo "$TARGET_DIR/emacs-eclim"
}

install() {
	git clone git://github.com/senny/emacs-eclim.git
}

remove() {
	rm -vrf $(target)
}

eval $1
