#!/bin/bash

require() {
	echo ""
}

description() {
	echo ""
}

target() {
	echo "$TARGET_DIR/el-get"
}

install() {
	git clone git://github.com/dimitri/el-get.git
}

remove() {
	rm -vrf $(target)
}

eval $1
