#!/bin/bash

require() {
	echo ""
}

description() {
	echo ""
}

target() {
	echo "$TARGET_DIR/rinari"
}

install() {
	git clone git://github.com/eschulte/rinari.git
	cd rinari && git submodule init && git submodule update
}

remove() {
	rm -vrf $(target)
}

eval $1
