#!/bin/bash

require() {
	echo ""
}

description() {
	echo ""
}

target() {
	echo "$TARGET_DIR/simplenote.el"
}

install() {
	git clone git://github.com/cefstat/simplenote.el.git
}

remove() {
	rm -vrf $(target)
}

eval $1
