#!/bin/bash

require() {
	echo ""
}

description() {
	echo ""
}

target() {
	echo "$TARGET_DIR/slime"
}

install() {
	git clone git://github.com/slime/slime.git
}

remove() {
	rm -vrf $(target)
}

eval $1
