#!/bin/bash

require() {
	echo "dropdown-list"
}

description() {
	echo ""
}

target() {
	echo "$TARGET_DIR/yasnippet"
}

install() {
	git clone git://github.com/capitaomorte/yasnippet.git &&
	cd yasnippet &&
	git submodule init &&
	git submodule update
}

remove() {
	rm -vrf $(target)
}

eval $1
