#!/bin/bash

require() {
	echo ""
}

description() {
	echo ""
}

target() {
	echo "$TARGET_DIR/yasobjc"
}

install() {
	git clone git://github.com/roupam/yasobjc.git
}

remove() {
	rm -vrf $(target)
}

eval $1
